### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by asdzheng** [Jude95/SwipeBackHelper#15]
java.lang.NullPointerException
    at android.view.GLES20RecordingCanvas.drawBitmap(GLES20RecordingCanvas.java:118)
    at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:393)
    at com.ningmilib.swipeback.SwipeBackLayout.drawShadow(SourceFile:314)
    at com.ningmilib.swipeback.SwipeBackLayout.drawChild(SourceFile:293)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
    at android.view.View.getDisplayList(View.java:10420)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2597)
    at android.view.View.getDisplayList(View.java:10385)
    at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:849)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:1910)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1634)
    at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2442)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4424)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
    at dalvik.system.NativeStart.main(Native Method)

这是在阿里云测测试结果里出现的问题。

**Comment by Jude95** [comment]
好的，可能要等最近一波忙过了再更新这些开源库。

**Comment by Jude95** [comment]
(๑ŐдŐ)b   google好久都找不到解。你知道什么吗。。真机出现过问题没。

**Comment by asdzheng** [comment]
真机还没出现过，要不等出现了我再来报告一下。

**Comment by Jude95** [comment]
好的。
