### ISSUE TITLE
Fatal Exception: java.lang.StackOverflowError

### ISSUE THREAD

**Issue by lightom13** [Jude95/SwipeBackHelper#42]
Fatal Exception: java.lang.StackOverflowError
       at android.graphics.Paint.set(Paint.java:437)
       at android.view.GLES20Canvas.drawText(GLES20Canvas.java:1010)
       at android.view.GLES20RecordingCanvas.drawText(GLES20RecordingCanvas.java:256)
       at android.text.Layout.draw(Layout.java:422)
       at android.widget.TextView.onDraw(TextView.java:5082)
       at android.view.View.draw(View.java:11015)
       at android.view.View.getDisplayList(View.java:10454)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.getDisplayList(View.java:10452)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.getDisplayList(View.java:10452)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.draw(View.java:11018)
       at android.support.v4.view.ViewPager.draw(ViewPager.java:2415)
       at android.view.View.getDisplayList(View.java:10454)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.getDisplayList(View.java:10452)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.getDisplayList(View.java:10452)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.getDisplayList(View.java:10452)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.draw(View.java:11018)
       at android.view.View.getDisplayList(View.java:10454)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:3838)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.draw(View.java:11018)
       at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3308)
       at android.view.View.getDisplayList(View.java:10454)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2588)
       at android.view.View.draw(View.java:11018)
       at android.view.View.getDisplayList(View.java:10454)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.getDisplayList(View.java:10452)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.getDisplayList(View.java:10452)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.draw(View.java:11018)
       at android.support.v4.view.ViewPager.draw(ViewPager.java:2415)
       at android.view.View.getDisplayList(View.java:10454)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.getDisplayList(View.java:10452)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.draw(View.java:11018)
       at android.widget.FrameLayout.draw(FrameLayout.java:450)
       at android.view.View.getDisplayList(View.java:10454)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.draw(View.java:11018)
       at android.support.v4.view.ViewPager.draw(ViewPager.java:2415)
       at android.view.View.getDisplayList(View.java:10454)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.getDisplayList(View.java:10452)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.getDisplayList(View.java:10452)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.draw(View.java:11018)
       at android.widget.FrameLayout.draw(FrameLayout.java:450)
       at android.view.View.getDisplayList(View.java:10454)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.getDisplayList(View.java:10452)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.getDisplayList(View.java:10452)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.draw(View.java:11018)
       at android.view.View.getDisplayList(View.java:10454)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       **# at com.jude.swipbackhelper.SwipeBackLayout.drawChild(SwipeBackLayout.java:292)**
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.getDisplayList(View.java:10452)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2942)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2581)
       at android.view.View.draw(View.java:11018)
       at android.widget.FrameLayout.draw(FrameLayout.java:450)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2167)
       at android.view.View.getDisplayList(View.java:10454)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:858)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2089)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1787)
       at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2642)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4647)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
       at dalvik.system.NativeStart.main(NativeStart.java)

看起来是绘制的嵌套太深了，导致栈溢出了。
能不能先try catch一下？

**Comment by Jude95** [comment]
...这锅我不背
