### ISSUE TITLE
崩溃问题

### ISSUE THREAD

**Issue by klqxx** [Jude95/SwipeBackHelper#68]
java.lang.IllegalStateException: Layout state should be one of 100 but it is 10
2
    at android.support.v7.widget.RecyclerView$s.a(RecyclerView.java:11903)
3
    at android.support.v7.widget.RecyclerView.O(RecyclerView.java:3829)
4
    at android.support.v7.widget.RecyclerView.q(RecyclerView.java:3540)
5
    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
6
    at android.view.View.layout(View.java)
7
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
8
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
9
    at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
10
    at android.view.View.layout(View.java)
11
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
12
    at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
13
    at android.view.View.layout(View.java)
14
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
15
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
16
    at android.view.View.layout(View.java)
17
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
18
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
19
    at android.view.View.layout(View.java)
20
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
21
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
22
    at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
23
    at android.view.View.layout(View.java)
24
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
25
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
26
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
27
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
28
    at android.view.View.layout(View.java)
29
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
30
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
31
    at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
32
    at android.view.View.layout(View.java)
33
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
34
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
35
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
36
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
37
    at android.view.View.layout(View.java)
38
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
39
    at com.jude.swipbackhelper.SwipeBackLayout.onLayout(SwipeBackLayout.java:275)
40
    at android.view.View.layout(View.java)
41
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
42
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
43
    at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
44
    at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2934)
45
    at android.view.View.layout(View.java)
46
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
47
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2179)
48
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1939)
49
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
50
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
51
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
52
    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
53
    at android.view.Choreographer.doFrame(Choreographer.java:606)
54
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
55
    at android.os.Handler.handleCallback(Handler.java:739)
56
    at android.os.Handler.dispatchMessage(Handler.java:95)
57
    at android.os.Looper.loop(Looper.java:148)
58
    at com.isen.radar.g.d$1.run(CrashHandler.java:58)
59
    at android.os.Handler.handleCallback(Handler.java:739)
60
    at android.os.Handler.dispatchMessage(Handler.java:95)
61
    at android.os.Looper.loop(Looper.java:148)
62
    at android.app.ActivityThread.main(ActivityThread.java:5461)
63
    at java.lang.reflect.Method.invoke(Native Method)
64
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
65
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
66

**Comment by klqxx** [comment]
java.lang.IllegalStateException: Layout state should be one of 100 but it is 10

at com.jude.swipbackhelper.SwipeBackLayout.onLayout(SwipeBackLayout.java:275)

**Comment by why168** [comment]
# Fix bug

@Jude95 

```log
java.lang.NullPointerException
Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference

android.widget.FrameLayout.layoutChildren(FrameLayout.java:275)
android.widget.FrameLayout.onLayout(FrameLayout.java:261)
android.view.View.layout(View.java:19941)
android.view.ViewGroup.layout(ViewGroup.java:6181)
android.widget.LinearLayout.setChildFrame(LinearLayout.java:1807)
android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
android.view.View.layout(View.java:19941)
android.view.ViewGroup.layout(ViewGroup.java:6181)
android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
android.widget.FrameLayout.onLayout(FrameLayout.java:261)
android.view.View.layout(View.java:19941)
android.view.ViewGroup.layout(ViewGroup.java:6181)
android.widget.LinearLayout.setChildFrame(LinearLayout.java:1807)
android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
android.view.View.layout(View.java:19941)
android.view.ViewGroup.layout(ViewGroup.java:6181)

com.jude.swipbackhelper.SwipeBackLayout.onLayout(Unknown Source:27)

android.view.View.layout(View.java:19941)
android.view.ViewGroup.layout(ViewGroup.java:6181)
android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
android.widget.FrameLayout.onLayout(FrameLayout.java:261)
com.android.internal.policy.DecorView.onLayout(DecorView.java:873)
android.view.View.layout(View.java:19941)
android.view.ViewGroup.layout(ViewGroup.java:6181)
android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2832)
android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2497)
android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1626)
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7406)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1005)
android.view.Choreographer.doCallbacks(Choreographer.java:817)
android.view.Choreographer.doFrame(Choreographer.java:752)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:991)
android.os.Handler.handleCallback(Handler.java:790)
android.os.Handler.dispatchMessage(Handler.java:99)
android.os.Looper.loop(Looper.java:198)
android.app.ActivityThread.main(ActivityThread.java:7015)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:521)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)
```
