### ISSUE TITLE
请教一下，与SwipeRefreshLayout搭配会报异常，但是不影响，是什么原因？

### ISSUE THREAD

**Issue by wudashan** [Jude95/SwipeBackHelper#8]
```
package com.example.administrator.myapplication;

import android.os.Bundle;
import android.os.Handler;
import android.support.v4.widget.SwipeRefreshLayout;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.Menu;
import android.view.MenuItem;

import com.jude.swipbackhelper.SwipeBackHelper;


public class MainActivity extends AppCompatActivity {

    private SwipeRefreshLayout mSwipeRefreshLayout;
    private Handler mHandler;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        SwipeBackHelper.onCreate(this);
        mHandler = new Handler();


        mSwipeRefreshLayout = (SwipeRefreshLayout) findViewById(R.id.mSwipeRefreshLayout);
        mSwipeRefreshLayout.setColorSchemeResources(android.R.color.holo_blue_bright);
        mSwipeRefreshLayout.setProgressViewOffset(false,300,500);
        mSwipeRefreshLayout.setOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener() {
            @Override
            public void onRefresh() {
                mSwipeRefreshLayout.setRefreshing(true);

                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        try {
                            Thread.sleep(1000);
                            mHandler.post(new Runnable() {
                                @Override
                                public void run() {
                                    mSwipeRefreshLayout.setRefreshing(false);
                                }
                            });
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }

                    }
                }).start();
            }
        });

        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);


    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }

    @Override
    protected void onPostCreate(Bundle savedInstanceState) {
        super.onPostCreate(savedInstanceState);
        SwipeBackHelper.onPostCreate(this);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        SwipeBackHelper.onDestroy(this);
    }
}
```

**Comment by Jude95** [comment]
报什么异常？
不使用我的库就就正常？

**Comment by wudashan** [comment]
```
11-10 09:04:30.108 2065-2065/? W/System.err: java.lang.IllegalArgumentException: pointerIndex out of range
11-10 09:04:30.108 2065-2065/? W/System.err:     at android.view.MotionEvent.nativeGetAxisValue(Native Method)
11-10 09:04:30.108 2065-2065/? W/System.err:     at android.view.MotionEvent.getX(MotionEvent.java:2057)
11-10 09:04:30.109 2065-2065/? W/System.err:     at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
11-10 09:04:30.109 2065-2065/? W/System.err:     at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:110)
11-10 09:04:30.109 2065-2065/? W/System.err:     at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:462)
11-10 09:04:30.109 2065-2065/? W/System.err:     at com.jude.swipbackhelper.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1095)
11-10 09:04:30.109 2065-2065/? W/System.err:     at com.jude.swipbackhelper.SwipeBackLayout.onInterceptTouchEvent(SwipeBackLayout.java:245)
11-10 09:04:30.109 2065-2065/? W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
11-10 09:04:30.110 2065-2065/? W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
11-10 09:04:30.110 2065-2065/? W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
11-10 09:04:30.110 2065-2065/? W/System.err:     at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
11-10 09:04:30.110 2065-2065/? W/System.err:     at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
11-10 09:04:30.110 2065-2065/? W/System.err:     at android.app.Activity.dispatchTouchEvent(Activity.java:2765)
11-10 09:04:30.110 2065-2065/? W/System.err:     at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
11-10 09:04:30.110 2065-2065/? W/System.err:     at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
11-10 09:04:30.110 2065-2065/? W/System.err:     at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
11-10 09:04:30.110 2065-2065/? W/System.err:     at android.view.View.dispatchPointerEvent(View.java:9514)
11-10 09:04:30.110 2065-2065/? W/System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
11-10 09:04:30.110 2065-2065/? W/System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
11-10 09:04:30.110 2065-2065/? W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
11-10 09:04:30.111 2065-2065/? W/System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
11-10 09:04:30.111 2065-2065/? W/System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
11-10 09:04:30.111 2065-2065/? W/System.err:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
11-10 09:04:30.111 2065-2065/? W/System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
11-10 09:04:30.111 2065-2065/? W/System.err:     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
11-10 09:04:30.111 2065-2065/? W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
11-10 09:04:30.111 2065-2065/? W/System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
11-10 09:04:30.111 2065-2065/? W/System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
11-10 09:04:30.111 2065-2065/? W/System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
11-10 09:04:30.111 2065-2065/? W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
11-10 09:04:30.111 2065-2065/? W/System.err:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
11-10 09:04:30.112 2065-2065/? W/System.err:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
11-10 09:04:30.112 2065-2065/? W/System.err:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
11-10 09:04:30.112 2065-2065/? W/System.err:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
11-10 09:04:30.112 2065-2065/? W/System.err:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
11-10 09:04:30.112 2065-2065/? W/System.err:     at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
11-10 09:04:30.112 2065-2065/? W/System.err:     at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
11-10 09:04:30.112 2065-2065/? W/System.err:     at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5996)
11-10 09:04:30.112 2065-2065/? W/System.err:     at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6048)
11-10 09:04:30.112 2065-2065/? W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
11-10 09:04:30.112 2065-2065/? W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
11-10 09:04:30.112 2065-2065/? W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:600)
11-10 09:04:30.112 2065-2065/? W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
11-10 09:04:30.112 2065-2065/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
11-10 09:04:30.112 2065-2065/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-10 09:04:30.113 2065-2065/? W/System.err:     at android.os.Looper.loop(Looper.java:148)
11-10 09:04:30.113 2065-2065/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
11-10 09:04:30.113 2065-2065/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-10 09:04:30.113 2065-2065/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-10 09:04:30.113 2065-2065/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-10 09:04:30.118 2065-2065/? I/ViewDragHelper: shouldInterceptTouchEvent：2
11-10 09:04:30.118 2065-2065/? I/ViewDragHelper: mDragState：3
```

**Comment by wudashan** [comment]
是的 把三个生命周期函数注释掉就不会报错

**Comment by Jude95** [comment]
确定是2.1.1版本吗。我刚试正常。。

**Comment by wudashan** [comment]
是啊，主要是配合SwipeRefreshLayout控件的时候会报异常，单独使用这两个都没事。

**Comment by Jude95** [comment]
感谢反馈，确实是个BUG。已修复。看看2.1.2还有没有问题。

**Comment by wudashan** [comment]
测试成功！感谢！请问能否注释一下Log？

```
11-10 12:23:50.217 2066-2066/? I/ViewDragHelper: return true
```

**Comment by Jude95** [comment]
好的，已删。。Log打的太多，删漏了。

**Comment by wudashan** [comment]
嗯嗯，非常感谢！

**Comment by wudashan** [comment]
你好，想问一下，主要是什么原因造成的报错？

**Comment by Jude95** [comment]
。。竖向手势时，是应该忽略的手势。但忽略时忘了改变一个变量。导致后面依然处理了一连串不应该处理的手势。

**Comment by wudashan** [comment]
噢，好的！
